### ISSUE TITLE
Unlocks fine, flashes great, but doesn't boot- ping only

### ISSUE THREAD

**Issue by strusty** [true-systems/om5p-ac-v2-unlocker#6]
The SSH unlocker worked just fine.

The AP51-flash worked great with the current OpenWRT firmware:

[f8:d9:b8:04:dd:a1]: OM5P-AC router: tftp client asks for 'fwupgrade.cfg', serving fwupgrade.cfg portion of: ./openwrt-18.06.1-ar71xx-generic-om5pac-squashfs-factory.bin (2 blocks) ...
[f8:d9:b8:04:dd:a1]: OM5P-AC router: tftp client asks for 'kernel', serving kernel portion of: ./openwrt-18.06.1-ar71xx-generic-om5pac-squashfs-factory.bin (2671 blocks) ...
[f8:d9:b8:04:dd:a1]: OM5P-AC router: tftp client asks for 'rootfs', serving rootfs portion of: ./openwrt-18.06.1-ar71xx-generic-om5pac-squashfs-factory.bin (5121 blocks) ...
[f8:d9:b8:04:dd:a1]: OM5P-AC router: image successfully transmitted - writing image to flash ...
[f8:d9:b8:04:dd:a1]: OM5P-AC router: flash complete. Device ready to unplug.

However, after reboot it is dead in the water:

root@gopi:~# nmap 172.16.16.22

Starting Nmap 7.60 ( https://nmap.org ) at 2018-11-10 14:17 IST
Nmap scan report for 172.16.16.22
Host is up (0.00041s latency).
All 1000 scanned ports on 172.16.16.22 are closed
MAC Address: F8:D9:B8:04:DD:A1 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 93.30 seconds

**Comment by pepe2k** [comment]
Hi @strusty,

Your question doesn't seem to be related to this project. If the flashing went fine and you installed one of the upstream versions of the OpenWrt... then you should probably start from reading https://openwrt.org/faq/start

> root@gopi:~# nmap 172.16.16.22

I have no idea what are you trying to do here.
OpenWrt uses 192.168.1.1/24 by default for LAN, with SSH enabled.

Cheers,
Piotr

**Comment by strusty** [comment]
Of course it does.  lol.  Yes, it worked fine, thank you for your work on
this.

Stuart

Status
System
Hostname
OpenWrt
Model
OpenMesh OM5P ACv2
Architecture
Qualcomm Atheros QCA9558 ver 1 rev 0
Firmware Version
OpenWrt 18.06.1 r7258-5eb055306f / LuCI openwrt-18.06 branch
(git-18.228.31946-f64b152)
Kernel Version
4.9.120
Local Time
Sat Nov 10 09:45:41 2018
Uptime
0h 6m 23s
Load Average
